-- Run this in your Supabase SQL Editor to create the vertical_workflow_steps table and update tasks

-- 1. Create vertical_workflow_steps table
create table if not exists public.vertical_workflow_steps (
  id bigint generated by default as identity primary key,
  vertical_id bigint references public.verticals(id) on delete cascade not null,
  role_id bigint references public.roles(id) on delete cascade not null,
  order_index integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.vertical_workflow_steps enable row level security;

-- Policies (everyone can view and edit, assuming workspace members are trusted. You can restrict to admins if needed)
create policy "Allow all operations for authenticated users on vertical_workflow_steps"
  on public.vertical_workflow_steps for all to authenticated using (true) with check (true);

-- 2. Add current_step_index to tasks table
alter table public.tasks 
add column if not exists current_step_index integer default 0;

