-- Run this in your Supabase SQL Editor to create the default_mini_tasks table

create table if not exists public.default_mini_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  order_index integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.default_mini_tasks enable row level security;

-- Policies (everyone can view and edit, assuming workspace members are trusted. You can restrict to admins if needed)
create policy "Allow all operations for authenticated users on default_mini_tasks"
  on public.default_mini_tasks for all to authenticated using (true) with check (true);

-- Insert initial data
insert into public.default_mini_tasks (title, description, order_index) values
  ('Type', 'Reel', 0),
  ('Posting Date', null, 1),
  ('Topic', null, 2),
  ('Content', null, 3),
  ('Caption', null, 4),
  ('REFERENCE VIDEO / Graphic LINKS', null, 5),
  ('Shoot Done?', null, 6),
  ('Ads', null, 7),
  ('Edited Post Link', null, 8),
  ('Instagram Link', null, 9),
  ('YouTube Long Link', null, 10),
  ('YouTube Shorts Link', null, 11),
  ('GMB Posting Link', null, 12),
  ('Add Workflow Statuses', null, 13)
on conflict do nothing;
